export const pptThemes = {
  maroon: {
    id: "maroon",
    name: "Classic SSC (Maroon & Gold)",
    slideBg: "#FFFFFF",
    headerBg: "#7A0000",
    qBadgeBg: "#FFFFFF",
    qBadgeColor: "#7A0000",
    examColor: "#FFFFFF",
    topicColor: "#FFD700",
    engColor: "#111111",
    dividerColor: "#A30000",
    hindiColor: "#7A0000",
    optionCardBg: "#FFFFFF",
    optionBorderColor: "#CBD5E1",
    optionBadgeBg: "#7A0000",
    optionBadgeColor: "#FFFFFF",
    optionTextColor: "#111111",
    footerBg: "#7A0000",
    footerColor: "#FFFFFF",
  },
  navy: {
    id: "navy",
    name: "Royal Navy & Cyan (EdTech)",
    slideBg: "#FFFFFF",
    headerBg: "#0A1931",
    qBadgeBg: "#FFFFFF",
    qBadgeColor: "#0A1931",
    examColor: "#FFFFFF",
    topicColor: "#00E5FF",
    engColor: "#0F172A",
    dividerColor: "#1E3A8A",
    hindiColor: "#1E3A8A",
    optionCardBg: "#FFFFFF",
    optionBorderColor: "#CBD5E1",
    optionBadgeBg: "#0A1931",
    optionBadgeColor: "#FFFFFF",
    optionTextColor: "#0F172A",
    footerBg: "#0A1931",
    footerColor: "#FFFFFF",
  },
  emerald: {
    id: "emerald",
    name: "Emerald Green (Exam Pro)",
    slideBg: "#FFFFFF",
    headerBg: "#064E3B",
    qBadgeBg: "#FFFFFF",
    qBadgeColor: "#064E3B",
    examColor: "#FFFFFF",
    topicColor: "#FDE047",
    engColor: "#111827",
    dividerColor: "#047857",
    hindiColor: "#065F46",
    optionCardBg: "#FFFFFF",
    optionBorderColor: "#D1D5DB",
    optionBadgeBg: "#064E3B",
    optionBadgeColor: "#FFFFFF",
    optionTextColor: "#111827",
    footerBg: "#064E3B",
    footerColor: "#FFFFFF",
  },
  dark: {
    id: "dark",
    name: "Dark Mode (Digital Board / YouTube)",
    slideBg: "#0B0F17",
    headerBg: "#111827",
    qBadgeBg: "#2563EB",
    qBadgeColor: "#FFFFFF",
    examColor: "#F3F4F6",
    topicColor: "#10B981",
    engColor: "#FFFFFF",
    dividerColor: "#1F2937",
    hindiColor: "#FBBF24",
    optionCardBg: "#1F2937",
    optionBorderColor: "#374151",
    optionBadgeBg: "#E11D48",
    optionBadgeColor: "#FFFFFF",
    optionTextColor: "#FFFFFF",
    footerBg: "#111827",
    footerColor: "#9CA3AF",
    examTagBg: "#DC2626",
    examTagColor: "#FFFFFF",
    examTagPosition: "below-question",
    examTagStyle: "pill",
    optionStyle: "clean",
  }
};

export const defaultPptSettings = {
  theme: "maroon",
  topic: "RATIO & PROPORTION",
  defaultExam: "SSC CGL 12/09/2025 (Shift 1)",
  layoutPreset: "full-width",
  boxPosX: 0,
  boxPosY: 0,
  engPosX: 0,
  engPosY: 0,
  engWidth: 100,
  hindiPosX: 0,
  hindiPosY: 0,
  hindiWidth: 100,
  examTagPosX: 0,
  examTagPosY: 0,
  examTagPosition: "below-question",
  examTagStyle: "pill",
  examTagBg: "#DC2626",
  examTagColor: "#FFFFFF",
  optionsPosX: 0,
  optionsPosY: 0,
  optionStyle: "card",
  examBadgeStyle: "text",
  headerHeight: 64,
  qBadgeShape: "pill",
  qBadgeSize: 18,
  examFontSize: 19,
  topicFontSize: 20,
  topicPosX: 0,
  topicPosY: 0,
  engFontSize: 19,
  engFontFamily: "Segoe UI, Arial, sans-serif",
  hindiFontSize: 18,
  hindiFontFamily: "Mangal, Noto Sans Devanagari, Nirmala UI, Arial, sans-serif",
  dividerThickness: 2,
  dividerWidth: 100,
  dividerPosX: 0,
  showDivider: true,
  optionColumns: 2,
  optionsLayout: "2-col",
  optionFontSize: 18,
  optionCardRadius: 8,
  optionCardBorderWidth: 1.5,
  optionCardPadding: 8,
  optionGap: 12,
  optionDynamicWidth: true,
  optionDynamicHeight: true,
  optionWidthPercent: 96,
  questionBoxWidth: 100,
  questionPadding: 16,
  dividerSpacing: 6,
  lineHeight: 1.36,
  showFooter: true,
  footerText: "Maths by Aditya | Telegram: @YourChannel",
  footerHeight: 28,
  footerFontSize: 13,
  aspectRatio: "16:9",
  applyScope: "all", // "all" = All Slides, "current" = Selected Slide Only
  ...pptThemes.maroon,
};

export function getSlideSettings(globalSettings = {}, q = {}) {
  if (!q || !q.settings || Object.keys(q.settings).length === 0) {
    return globalSettings;
  }
  return { ...globalSettings, ...q.settings };
}

export const sampleQuestions = [
  {
    id: "q_1",
    number: "Q.1",
    topic: "RATIO & PROPORTION",
    exam: "SSC CGL 12/09/2025 (Shift 2)",
    english: "The number of red, blue, and green marbles in a bag is in the ratio 3 : 4 : 6. If 25 red marbles, 15 blue marbles, and an unknown number of green marbles are added to the bag, the ratio of red, blue, and green marbles becomes 4 : 5 : 9. Determine the number of green marbles added.",
    hindi: "एक बैग में लाल, नीले और हरे कंचों की संख्या का अनुपात 3 : 4 : 6 है। यदि बैग में 25 लाल कंचे, 15 नीले कंचे और अज्ञात संख्या में हरे कंचे जोड़े जाते हैं, तो लाल, नीले और हरे कंचों का अनुपात 4 : 5 : 9 हो जाता है। जोड़े गए हरे कंचों की संख्या ज्ञात कीजिए।",
    options: [
      { key: "A", text: "103" },
      { key: "B", text: "110" },
      { key: "C", text: "107" },
      { key: "D", text: "105" }
    ],
    answer: "B"
  },
  {
    id: "q_2",
    number: "Q.2",
    topic: "PARTNERSHIP",
    exam: "SSC CGL 12/09/2025 (Shift 1)",
    english: "Sonu started a business by investing ₹40,000. After 4 months, Prem joined with ₹80,000. At the end of 8 months from the start, Alok joined with ₹1,20,000. If the total profit is ₹1,56,000 at the end of the year, find the share of Alok.",
    hindi: "सोनू ने ₹40,000 का निवेश करके एक व्यवसाय शुरू किया। 4 महीने बाद, प्रेम ₹80,000 के साथ शामिल हुआ। शुरुआत से 8 महीने के अंत में, आलोक ₹1,20,000 के साथ शामिल हुआ। यदि वर्ष के अंत में कुल लाभ ₹1,56,000 है, तो आलोक का हिस्सा ज्ञात कीजिए।",
    options: [
      { key: "A", text: "₹47,500" },
      { key: "B", text: "₹48,000" },
      { key: "C", text: "₹47,200" },
      { key: "D", text: "₹46,800" }
    ],
    answer: "B"
  }
];