export const previewBranch = {
  id: "preview",
  defaultFontSize: 38,
  minFontSize: 22,
  maxFontSize: 72,
  defaultFontFamily: "Arial",
  defaultTextColor: "#050505",
  defaultHighlightColor: "#fff3a3",
  defaultLineHeight: 1.2,
  defaultAlignment: "left",
  defaultDrawingStroke: "#176b87",
  defaultDrawingFill: "#e9f6f8",
  defaultDrawingStrokeWidth: 5,
  defaultDrawingFillOpacity: 0.85,
  defaultDrawingOpacity: 1,
  defaultDrawingLineStyle: "solid",
  defaultDrawingLineCap: "round",
  defaultDrawingLineJoin: "round",
  defaultBackground: "#ffffff",
};
