export const toolBranch = {
  id: "tools",
  title: "Figure Tools",
  subtitle: "Geometry, mensuration and labels",
  groups: [
    {
      id: "geometry-shapes",
      title: "Geometry Shapes",
      subtitle: "2D drawing templates",
      items: [
        {
          id: "point",
          title: "Point",
          meta: "Coordinate marker",
          kind: "Shape",
          latex: "A(x,y)",
          figure: {
            formula: "A(x, y)",
            viewBox: "0 0 220 150",
            svg: '<circle class="shape-fill-accent" cx="110" cy="75" r="7"></circle><text x="122" y="70">A(x,y)</text>',
          },
        },
        {
          id: "line-segment",
          title: "Line Segment",
          meta: "Segment AB",
          kind: "Shape",
          latex: "AB=l",
          figure: {
            formula: "AB = l",
            viewBox: "0 0 220 150",
            svg: '<line class="shape-line" x1="35" y1="82" x2="185" y2="82"></line><circle class="shape-point" cx="35" cy="82" r="4"></circle><circle class="shape-point" cx="185" cy="82" r="4"></circle><text x="27" y="105">A</text><text x="180" y="105">B</text><text x="102" y="69">l</text>',
          },
        },
        {
          id: "ray",
          title: "Ray",
          meta: "Ray AB",
          kind: "Shape",
          latex: "\\overline{AB}",
          figure: {
            formula: "Ray AB",
            viewBox: "0 0 220 150",
            svg: '<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="currentColor"></path></marker></defs><line class="shape-line" marker-end="url(#arrow)" x1="42" y1="82" x2="178" y2="82"></line><circle class="shape-point" cx="42" cy="82" r="4"></circle><text x="34" y="106">A</text><text x="174" y="106">B</text>',
          },
        },
        {
          id: "angle",
          title: "Angle",
          meta: "Angle ABC",
          kind: "Shape",
          latex: "\\angle ABC=\\theta",
          figure: {
            formula: "angle ABC = theta",
            viewBox: "0 0 220 150",
            svg: '<path class="shape-line" d="M58 112 L98 72 L174 72"></path><path class="shape-arc" d="M82 88 A26 26 0 0 0 124 72"></path><text x="51" y="130">A</text><text x="92" y="64">B</text><text x="176" y="77">C</text><text x="104" y="96">theta</text>',
          },
        },
        {
          id: "triangle",
          title: "Triangle",
          meta: "Base and height",
          kind: "Shape",
          latex: "A=\\frac{1}{2}bh",
          figure: {
            formula: "A = 1/2 bh",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="42,118 178,118 108,30"></polygon><line class="shape-dash" x1="108" y1="30" x2="108" y2="118"></line><text x="103" y="136">b</text><text x="114" y="78">h</text>',
          },
        },
        {
          id: "right-triangle",
          title: "Right Triangle",
          meta: "Pythagoras",
          kind: "Shape",
          latex: "a^2+b^2=c^2",
          figure: {
            formula: "a^2 + b^2 = c^2",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="58,118 58,35 170,118"></polygon><path class="shape-line-thin" d="M58 100 H76 V118"></path><text x="38" y="80">a</text><text x="105" y="137">b</text><text x="119" y="75">c</text>',
          },
        },
        {
          id: "equilateral-triangle",
          title: "Equilateral Triangle",
          meta: "All sides equal",
          kind: "Shape",
          latex: "A=\\frac{\\sqrt{3}}{4}a^2",
          figure: {
            formula: "A = sqrt(3)/4 a^2",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="110,28 42,122 178,122"></polygon><text x="67" y="81">a</text><text x="145" y="81">a</text><text x="105" y="139">a</text>',
          },
        },
        {
          id: "square",
          title: "Square",
          meta: "Area and perimeter",
          kind: "Shape",
          latex: "A=a^2,\\ P=4a",
          figure: {
            formula: "A = a^2, P = 4a",
            viewBox: "0 0 220 150",
            svg: '<rect class="shape-fill" x="67" y="32" width="86" height="86"></rect><text x="106" y="131">a</text><text x="48" y="78">a</text>',
          },
        },
        {
          id: "rectangle",
          title: "Rectangle",
          meta: "Length and width",
          kind: "Shape",
          latex: "A=lw,\\ P=2(l+w)",
          figure: {
            formula: "A = lw, P = 2(l + w)",
            viewBox: "0 0 220 150",
            svg: '<rect class="shape-fill" x="45" y="42" width="130" height="72"></rect><text x="105" y="130">l</text><text x="25" y="82">w</text>',
          },
        },
        {
          id: "parallelogram",
          title: "Parallelogram",
          meta: "Base and height",
          kind: "Shape",
          latex: "A=bh",
          figure: {
            formula: "A = bh",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="66,38 178,38 154,116 42,116"></polygon><line class="shape-dash" x1="154" y1="38" x2="154" y2="116"></line><text x="96" y="132">b</text><text x="161" y="82">h</text>',
          },
        },
        {
          id: "rhombus",
          title: "Rhombus",
          meta: "Diagonals",
          kind: "Shape",
          latex: "A=\\frac{d_1d_2}{2}",
          figure: {
            formula: "A = d1 d2 / 2",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="110,22 178,75 110,128 42,75"></polygon><line class="shape-dash" x1="42" y1="75" x2="178" y2="75"></line><line class="shape-dash" x1="110" y1="22" x2="110" y2="128"></line><text x="103" y="71">d2</text><text x="117" y="77">d1</text>',
          },
        },
        {
          id: "trapezium",
          title: "Trapezium",
          meta: "Parallel sides",
          kind: "Shape",
          latex: "A=\\frac{1}{2}(a+b)h",
          figure: {
            formula: "A = 1/2 (a + b)h",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="76,38 148,38 180,116 40,116"></polygon><line class="shape-dash" x1="148" y1="38" x2="148" y2="116"></line><text x="108" y="31">a</text><text x="105" y="133">b</text><text x="154" y="82">h</text>',
          },
        },
        {
          id: "circle",
          title: "Circle",
          meta: "Radius and circumference",
          kind: "Shape",
          latex: "A=\\pi r^2,\\ C=2\\pi r",
          figure: {
            formula: "A = pi r^2, C = 2pi r",
            viewBox: "0 0 220 150",
            svg: '<circle class="shape-fill" cx="110" cy="75" r="48"></circle><line class="shape-line-thin" x1="110" y1="75" x2="158" y2="75"></line><circle class="shape-point" cx="110" cy="75" r="3"></circle><text x="132" y="68">r</text>',
          },
        },
        {
          id: "semicircle",
          title: "Semicircle",
          meta: "Half circle",
          kind: "Shape",
          latex: "A=\\frac{1}{2}\\pi r^2",
          figure: {
            formula: "A = 1/2 pi r^2",
            viewBox: "0 0 220 150",
            svg: '<path class="shape-fill" d="M55 102 A55 55 0 0 1 165 102 Z"></path><line class="shape-line-thin" x1="110" y1="102" x2="165" y2="102"></line><text x="134" y="95">r</text>',
          },
        },
        {
          id: "sector",
          title: "Sector",
          meta: "Arc and angle",
          kind: "Shape",
          latex: "A=\\frac{\\theta}{360}\\pi r^2",
          figure: {
            formula: "A = theta/360 pi r^2",
            viewBox: "0 0 220 150",
            svg: '<path class="shape-fill" d="M110 112 L110 36 A76 76 0 0 1 179 80 Z"></path><path class="shape-arc" d="M121 97 A23 23 0 0 0 135 79"></path><text x="128" y="98">theta</text><text x="105" y="70">r</text>',
          },
        },
        {
          id: "ellipse",
          title: "Ellipse",
          meta: "Semi-axes",
          kind: "Shape",
          latex: "A=\\pi ab",
          figure: {
            formula: "A = pi ab",
            viewBox: "0 0 220 150",
            svg: '<ellipse class="shape-fill" cx="110" cy="76" rx="68" ry="38"></ellipse><line class="shape-dash" x1="42" y1="76" x2="178" y2="76"></line><line class="shape-dash" x1="110" y1="38" x2="110" y2="114"></line><text x="143" y="69">a</text><text x="116" y="55">b</text>',
          },
        },
        {
          id: "regular-polygon",
          title: "Regular Polygon",
          meta: "Interior angle sum",
          kind: "Shape",
          latex: "S=(n-2)180^\\circ",
          figure: {
            formula: "S = (n - 2)180 deg",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="110,24 166,55 166,112 110,140 54,112 54,55"></polygon><text x="100" y="86">n</text>',
          },
        },
      ],
    },
    {
      id: "mensuration",
      title: "Mensuration",
      subtitle: "2D and 3D measures",
      items: [
        {
          id: "cube",
          title: "Cube",
          meta: "Volume and surface area",
          kind: "Solid",
          latex: "V=a^3,\\ TSA=6a^2",
          figure: {
            formula: "V = a^3, TSA = 6a^2",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="62,56 124,56 158,30 96,30"></polygon><polygon class="shape-fill" points="124,56 158,30 158,94 124,122"></polygon><rect class="shape-fill" x="62" y="56" width="62" height="66"></rect><text x="88" y="138">a</text>',
          },
        },
        {
          id: "cuboid",
          title: "Cuboid",
          meta: "Length, breadth, height",
          kind: "Solid",
          latex: "V=lbh",
          figure: {
            formula: "V = lbh",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="46,62 142,62 174,38 78,38"></polygon><polygon class="shape-fill" points="142,62 174,38 174,104 142,128"></polygon><rect class="shape-fill" x="46" y="62" width="96" height="66"></rect><text x="88" y="143">l</text><text x="157" y="121">b</text><text x="30" y="96">h</text>',
          },
        },
        {
          id: "cylinder",
          title: "Cylinder",
          meta: "Circular prism",
          kind: "Solid",
          latex: "V=\\pi r^2h",
          figure: {
            formula: "V = pi r^2 h",
            viewBox: "0 0 220 150",
            svg: '<ellipse class="shape-fill" cx="110" cy="38" rx="52" ry="18"></ellipse><path class="shape-fill-soft" d="M58 38 V112 A52 18 0 0 0 162 112 V38"></path><ellipse class="shape-line-thin no-fill" cx="110" cy="112" rx="52" ry="18"></ellipse><line class="shape-line-thin" x1="110" y1="38" x2="162" y2="38"></line><text x="132" y="31">r</text><text x="169" y="78">h</text>',
          },
        },
        {
          id: "cone",
          title: "Cone",
          meta: "Radius and height",
          kind: "Solid",
          latex: "V=\\frac{1}{3}\\pi r^2h",
          figure: {
            formula: "V = 1/3 pi r^2 h",
            viewBox: "0 0 220 150",
            svg: '<path class="shape-fill" d="M110 24 L54 118 A56 18 0 0 0 166 118 Z"></path><ellipse class="shape-line-thin no-fill" cx="110" cy="118" rx="56" ry="18"></ellipse><line class="shape-dash" x1="110" y1="24" x2="110" y2="118"></line><line class="shape-line-thin" x1="110" y1="118" x2="166" y2="118"></line><text x="116" y="75">h</text><text x="135" y="111">r</text>',
          },
        },
        {
          id: "sphere",
          title: "Sphere",
          meta: "Radius",
          kind: "Solid",
          latex: "V=\\frac{4}{3}\\pi r^3",
          figure: {
            formula: "V = 4/3 pi r^3",
            viewBox: "0 0 220 150",
            svg: '<circle class="shape-fill" cx="110" cy="75" r="52"></circle><ellipse class="shape-dash no-fill" cx="110" cy="75" rx="52" ry="15"></ellipse><line class="shape-line-thin" x1="110" y1="75" x2="162" y2="75"></line><text x="135" y="68">r</text>',
          },
        },
        {
          id: "hemisphere",
          title: "Hemisphere",
          meta: "Half sphere",
          kind: "Solid",
          latex: "V=\\frac{2}{3}\\pi r^3",
          figure: {
            formula: "V = 2/3 pi r^3",
            viewBox: "0 0 220 150",
            svg: '<path class="shape-fill" d="M55 92 A55 55 0 0 1 165 92 A55 18 0 0 1 55 92 Z"></path><ellipse class="shape-line-thin no-fill" cx="110" cy="92" rx="55" ry="18"></ellipse><line class="shape-line-thin" x1="110" y1="92" x2="165" y2="92"></line><text x="135" y="85">r</text>',
          },
        },
        {
          id: "pyramid",
          title: "Pyramid",
          meta: "Base area and height",
          kind: "Solid",
          latex: "V=\\frac{1}{3}Bh",
          figure: {
            formula: "V = 1/3 Bh",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="110,24 48,112 154,130 178,82"></polygon><line class="shape-line-thin" x1="110" y1="24" x2="154" y2="130"></line><line class="shape-line-thin" x1="110" y1="24" x2="178" y2="82"></line><line class="shape-dash" x1="110" y1="24" x2="112" y2="102"></line><text x="118" y="72">h</text><text x="91" y="126">B</text>',
          },
        },
        {
          id: "frustum",
          title: "Frustum",
          meta: "Truncated cone",
          kind: "Solid",
          latex: "V=\\frac{1}{3}\\pi h(R^2+r^2+Rr)",
          figure: {
            formula: "V = 1/3 pi h(R^2 + r^2 + Rr)",
            viewBox: "0 0 220 150",
            svg: '<ellipse class="shape-fill" cx="110" cy="42" rx="34" ry="12"></ellipse><path class="shape-fill-soft" d="M76 42 L50 116 A60 18 0 0 0 170 116 L144 42"></path><ellipse class="shape-line-thin no-fill" cx="110" cy="116" rx="60" ry="18"></ellipse><line class="shape-dash" x1="110" y1="42" x2="110" y2="116"></line><text x="149" y="113">R</text><text x="116" y="35">r</text><text x="116" y="83">h</text>',
          },
        },
      ],
    },
    {
      id: "algebra",
      title: "Algebra",
      subtitle: "Equations and identities",
      items: [
        {
          id: "linear-equation",
          title: "Linear Equation",
          meta: "One variable",
          kind: "Formula",
          latex: "ax+b=0\\Rightarrow x=-\\frac{b}{a}",
        },
        {
          id: "quadratic-formula",
          title: "Quadratic Formula",
          meta: "Roots of ax^2+bx+c",
          kind: "Formula",
          latex: "x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}",
        },
        {
          id: "difference-squares",
          title: "Difference Of Squares",
          meta: "Factor identity",
          kind: "Formula",
          latex: "a^2-b^2=(a-b)(a+b)",
        },
        {
          id: "perfect-square",
          title: "Perfect Square",
          meta: "Expansion",
          kind: "Formula",
          latex: "(a+b)^2=a^2+2ab+b^2",
        },
        {
          id: "simultaneous-equations",
          title: "Simultaneous Equations",
          meta: "Two equation layout",
          kind: "Formula",
          latex: "\\begin{aligned}ax+by&=c\\\\dx+ey&=f\\end{aligned}",
        },
        {
          id: "ap-nth-term",
          title: "AP Nth Term",
          meta: "Arithmetic progression",
          kind: "Formula",
          latex: "a_n=a+(n-1)d",
        },
        {
          id: "gp-nth-term",
          title: "GP Nth Term",
          meta: "Geometric progression",
          kind: "Formula",
          latex: "a_n=ar^{n-1}",
        },
        {
          id: "two-by-two-matrix",
          title: "2 x 2 Matrix",
          meta: "Matrix template",
          kind: "Formula",
          latex: "\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}",
        },
      ],
    },
    {
      id: "trigonometry",
      title: "Trigonometry",
      subtitle: "Ratios and identities",
      items: [
        {
          id: "right-triangle-ratios",
          title: "Right Triangle Ratios",
          meta: "sin, cos, tan",
          kind: "Shape",
          latex: "\\sin\\theta=\\frac{p}{h},\\ \\cos\\theta=\\frac{b}{h},\\ \\tan\\theta=\\frac{p}{b}",
          figure: {
            formula: "sin(theta)=p/h, cos(theta)=b/h, tan(theta)=p/b",
            viewBox: "0 0 220 150",
            svg: '<polygon class="shape-fill" points="52,118 52,34 174,118"></polygon><path class="shape-arc" d="M72 118 A20 20 0 0 0 66 98"></path><text x="72" y="107">theta</text><text x="31" y="78">p</text><text x="105" y="137">b</text><text x="121" y="75">h</text>',
          },
        },
        {
          id: "pythagorean-identity",
          title: "Pythagorean Identity",
          meta: "Basic identity",
          kind: "Formula",
          latex: "\\sin^2\\theta+\\cos^2\\theta=1",
        },
        {
          id: "tan-identity",
          title: "Tan Identity",
          meta: "Ratio identity",
          kind: "Formula",
          latex: "\\tan\\theta=\\frac{\\sin\\theta}{\\cos\\theta}",
        },
        {
          id: "sine-rule",
          title: "Sine Rule",
          meta: "Triangle relation",
          kind: "Formula",
          latex: "\\frac{a}{\\sin A}=\\frac{b}{\\sin B}=\\frac{c}{\\sin C}",
        },
        {
          id: "cosine-rule",
          title: "Cosine Rule",
          meta: "Triangle relation",
          kind: "Formula",
          latex: "c^2=a^2+b^2-2ab\\cos C",
        },
        {
          id: "angle-sum-sine",
          title: "Sine Angle Sum",
          meta: "Expansion",
          kind: "Formula",
          latex: "\\sin(A+B)=\\sin A\\cos B+\\cos A\\sin B",
        },
        {
          id: "cos-double-angle",
          title: "Cos Double Angle",
          meta: "Identity",
          kind: "Formula",
          latex: "\\cos 2A=\\cos^2 A-\\sin^2 A",
        },
        {
          id: "unit-circle",
          title: "Unit Circle",
          meta: "Coordinates",
          kind: "Shape",
          latex: "x^2+y^2=1",
          figure: {
            formula: "x^2 + y^2 = 1",
            viewBox: "0 0 220 150",
            svg: '<circle class="shape-fill" cx="110" cy="75" r="48"></circle><line class="shape-axis" x1="38" y1="75" x2="182" y2="75"></line><line class="shape-axis" x1="110" y1="132" x2="110" y2="18"></line><line class="shape-line-thin" x1="110" y1="75" x2="151" y2="50"></line><text x="151" y="47">(cos t, sin t)</text>',
          },
        },
      ],
    },
    {
      id: "coordinate-geometry",
      title: "Coordinate Geometry",
      subtitle: "Graphs and coordinate formulas",
      items: [
        {
          id: "cartesian-plane",
          title: "Cartesian Plane",
          meta: "x-y axes",
          kind: "Shape",
          latex: "(x,y)",
          figure: {
            formula: "Point: (x, y)",
            viewBox: "0 0 220 150",
            svg: '<defs><marker id="axisArrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="currentColor"></path></marker></defs><line class="shape-axis" marker-end="url(#axisArrow)" x1="28" y1="118" x2="190" y2="118"></line><line class="shape-axis" marker-end="url(#axisArrow)" x1="58" y1="132" x2="58" y2="22"></line><circle class="shape-point" cx="138" cy="65" r="4"></circle><line class="shape-dash" x1="138" y1="65" x2="138" y2="118"></line><line class="shape-dash" x1="58" y1="65" x2="138" y2="65"></line><text x="145" y="61">(x,y)</text><text x="193" y="122">x</text><text x="49" y="18">y</text>',
          },
        },
        {
          id: "slope",
          title: "Slope",
          meta: "Two points",
          kind: "Formula",
          latex: "m=\\frac{y_2-y_1}{x_2-x_1}",
        },
        {
          id: "distance-formula",
          title: "Distance Formula",
          meta: "Two points",
          kind: "Formula",
          latex: "d=\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}",
        },
        {
          id: "midpoint-formula",
          title: "Midpoint Formula",
          meta: "Average of coordinates",
          kind: "Formula",
          latex: "M=\\left(\\frac{x_1+x_2}{2},\\frac{y_1+y_2}{2}\\right)",
        },
        {
          id: "line-equation",
          title: "Line Equation",
          meta: "Slope intercept",
          kind: "Formula",
          latex: "y=mx+c",
        },
        {
          id: "circle-equation",
          title: "Circle Equation",
          meta: "Center-radius form",
          kind: "Formula",
          latex: "(x-h)^2+(y-k)^2=r^2",
        },
        {
          id: "parabola",
          title: "Parabola",
          meta: "Standard form",
          kind: "Shape",
          latex: "y^2=4ax",
          figure: {
            formula: "y^2 = 4ax",
            viewBox: "0 0 220 150",
            svg: '<path class="shape-line" d="M72 32 C155 32 155 118 72 118"></path><line class="shape-axis" x1="40" y1="75" x2="182" y2="75"></line><line class="shape-axis" x1="72" y1="128" x2="72" y2="22"></line><circle class="shape-point" cx="104" cy="75" r="3"></circle><text x="109" y="69">F</text>',
          },
        },
      ],
    },
    {
      id: "calculus-statistics",
      title: "Calculus & Statistics",
      subtitle: "Common advanced templates",
      items: [
        {
          id: "limit",
          title: "Limit",
          meta: "Approach notation",
          kind: "Formula",
          latex: "\\lim_{x\\to a}f(x)=L",
        },
        {
          id: "derivative-power-rule",
          title: "Derivative Rule",
          meta: "Power rule",
          kind: "Formula",
          latex: "\\frac{d}{dx}x^n=nx^{n-1}",
        },
        {
          id: "definite-integral",
          title: "Definite Integral",
          meta: "Area under curve",
          kind: "Formula",
          latex: "\\int_a^b f(x)dx",
        },
        {
          id: "summation",
          title: "Summation",
          meta: "Sigma notation",
          kind: "Formula",
          latex: "\\sum_{i=1}^{n}i=\\frac{n(n+1)}{2}",
        },
        {
          id: "mean",
          title: "Mean",
          meta: "Average",
          kind: "Formula",
          latex: "\\bar{x}=\\frac{\\sum x_i}{n}",
        },
        {
          id: "probability",
          title: "Probability",
          meta: "Classical probability",
          kind: "Formula",
          latex: "P(A)=\\frac{n(A)}{n(S)}",
        },
      ],
    },
  ],
  authoring: {
    chapters: [],
    equationSnippets: [],
    drawToolGroups: [
      { id: "labels", title: "Labeling Tools", tools: ["label", "callout", "point", "line", "arrow", "double-arrow", "angle"] },
    ],
    drawTools: [
      { id: "label", label: "Label", title: "Text label box" },
      { id: "callout", label: "Callout", title: "Label with pointer arrow" },
      { id: "point", label: "Point", title: "Point marker" },
      { id: "crosshair", label: "Cross", title: "Crosshair marker" },
      { id: "line", label: "Line", title: "Straight line" },
      { id: "arrow", label: "Arrow", title: "Arrow marker" },
      { id: "double-arrow", label: "Measure", title: "Double-arrow measurement" },
      { id: "angle", label: "Angle", title: "Angle marker" },
      { id: "level-line", label: "Level", title: "Level guide line" },
      { id: "ruler", label: "Ruler", title: "Ruler ticks" },
      { id: "protractor", label: "Protractor", title: "Protractor arc" },
      { id: "axis", label: "Axis", title: "X-Y axis guide" },
      { id: "rectangle", label: "Rect", title: "Rectangle box" },
      { id: "circle", label: "Circle", title: "Circle outline" },
      { id: "ellipse", label: "Ellipse", title: "Ellipse outline" },
      { id: "triangle", label: "Triangle", title: "Triangle outline" },
      { id: "highlight", label: "Highlight", title: "Transparent highlight box" },
    ],
    labelPositions: [
      { id: "top", label: "Top" },
      { id: "right", label: "Right" },
      { id: "bottom", label: "Bottom" },
      { id: "center", label: "Center" },
    ],
    alignments: [
      { id: "left", label: "Left" },
      { id: "center", label: "Center" },
      { id: "right", label: "Right" },
    ],
  },
};
